services:
  mysql:
    image: mysql:8
    container_name: beegol-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: BeegolDatabase
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - beegol-data:/var/lib/mysql
volumes:
  beegol-data: